export class Contexto{
    constructor(
    public _id:string,
    
    public date: any,
    public image: any,
    public title: String,
    public content: String,
    public id_cont: String,
    public proyecto: String,
    public year_inv: Number,
    public investigador: String,
    public sector: String,
    public ubicacion: String,
    public operacion: String,
    public suboperacion: String,
    public desc_operacion: String,
    public cont: String,
    public diagnostico_contexto: String,
    public tipo_contexto: String,
    public otro_contexto: String,
    public num_cem: String,
    public num_basa: String,
    public num_plaza: String,
    public num_estruc: String,
    public ind_conex: String,
    public foto: String,
    public num_foto: String,
    public calidad_foto: String,
    public estado_foto: String,
    public planimetria: String,
    public num_lamina: String,
    public calidad_plano: String,
    public estado_plano: String,
    public coordenadas: String,
    public crtm: String,
    public profundidad: String,
    public profundidad_datum: String,
    public ubicacion_datum: String,
    public existe_antro: String,
    public estado_antro: String,
    public tipo_enterramiento: String,
    public forma_enterramiento: String,
    public condicion: String,
    public sexo:String,
    public edad:Number,
    public patologias:String,
    public evidencia: String,
    public fecha_existe: String,
    public tecnica: String,
    public material_fechado: String,
    public asociacion_indv: String,
    public asociacion_art: String,
    public num_lab: String,
    public fecha_conv: String,
    public fecha_calb: String,
    public valoracion_fecha: String,
    public explique_fecha: String,
    public otras_muestras: String,
    public estado_muestras: String,
    public cera_existe: String,
    public cera_cant: String,
    public id_artef_cera: String,
    public litica_existe: String,
    public litica_cant: String,
    public id_litica: String,
    public metal_existe: String,
    public metal_cantidad: String,
    public metal_id: String,
    public madera_existe: String,
    public madera_cantidad: String,
    public madera_id: String,
    public fauna_existe: String,
    public fauna_cantidad: String,
    public fauna_id: String,
    public otros_existe: String,
    public otros_cantidad: String,
    public otros_id: String,
    public verifica_si: String,
    public inves_verifica: String,
    public fecha_verifica: any,
    public resultados_verifica: String,
    public revisor_documental: String,
    public fecha_revision: any 


        ){}
}