export class Litico{
    constructor(
        public _id:string,
        public title:string,
        public image:any,
        public date:any,
        public content:string,
        public cod_mon:string,
        public num_artefacto:number,
        public num_caja:number,
        public proyecto:string,
        public investigador:string,
        public pro_year:number,
        public etiqueta:string,
        public fecha_exc:any,
        public id_contexto:string,
        public contexto:string,
        public ubicacion:string,
        public foto:string,
        public num_foto:string,
        public calidad_foto:string,
        public estado_foto:string,
        public plano:string,
        public num_lamina:string,
        public calidad_lamina:string,
        public estado_Lamina:string,
        public diagnostico_contexto:string,
        public fechamiento:string,

        public tipo_pieza: String,
        public desc_narrativa: String,
        public materia_prima: String,
        public lineas: String,
        public  greca: String,
        public elemento_secuencia: String,
        public otro_nofig: String,
        public cab_zoo: String,
        public suario_zoo: String,
        public felino_zoo: String,
        public batracio_zoo: String,
        public ave_zoo: String,
        public  primate_zoo: String,
        public  murcielago_zoo: String,
        public   mamifero_zoo: String,
        public  turtle_zoo: String,
        public  reptil_zoo: String,
        public  pez_zoo: String,
        public armadillo_zoo: String,
        public  insecto_zoo: String,
        public  ciervo_zoo: String,
        public canino_zoo: String,
        public ind_zoo: String,
        public  tax_zoo: String,
        public  inv_zoo: String,
        public cab_antro: String,
        public cab_tocantro: String,
        public masc_antro: String,
        public  atuendo_antro: String,
        public cara_antro: String,
        public sedente_antro: String,
        public  erguida_antro: String,
        public  supino_antro: String,
        public  escena_antro: String,
        public  genero_antro: String,
        public  anomalia_antro: String,
        public  cab_ind: String,
        public  cara_ind: String,
        public  otro_ind: String,
        public uso_funcion: String,
        public  datos_funcionalidad: String,
        public  datos_func_exp: String,
        public  referencias_funcional: String,
        public  periodo_funcional:  String,
        public  fase_funcional: String,
        public  temporalidad_funcional: String,
        public  procedencia_funcional: String,
        public  estado_conservacion: String,
        public  potencial: String,
        public  potencial_exp: String,
        public  largo: String,
        public  ancho: String,
        public  alto: String,
        public  peso: String,
        public  nombre_invest: String,
        public  fecha_analisis: String,
        public  fotos_num: String 

    ){}
}


