'use strict'

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var CeramicSchema = Schema({
    
    date: { type: Date, default: Date.now },
    image: String,
    title: String,
    content: String,
    cod_mon: String,
    num_artefacto: Number,
    num_caja: Number,
    proyecto: String,
    investigador: String,
    pro_year: Number,
    etiqueta: String,
    fecha_exc: Date,
    id_contexto: String,
    contexto: String,
    ubicacion: String,
    foto: String,
    num_foto: String,
    calidad_foto: String,
    estado_foto: String,
    plano: String,
    num_lamina: String,
    calidad_lamina: String,
    estado_Lamina: String,
    diagnostico_contexto: String,
    fechamiento: String,
    tipo_pieza: String,
    desc_narrativa: String,
    apendices: String,
    soporte: String,
    ped_base: String,
    asa: String,
    vtdero: String,
    otro_soporte: String,
    desc_apendice: String,
    acabado_superficie: String,
    estilo_decorativo: String,
    color_pintura: String,
    pre_coc: String,
    post_coc: String,
    esgraf: String,
    ptdo: String,
    tira_apl: String,
    ptll: String,
    zna: String,
    rndo: String,
    acnlo: String,
    hddo: String,
    ptdopt: String,
    mdl: String,
    vertical: String,
    horizontal: String,
    zig_zag: String,
    panel: String,
    aisld: String,
    str: String,
    otro_nofig: String,
    head: String,
    suario: String,
    felino: String,
    batracio: String,
    ave: String,
    primate: String,
    murcielago: String,
    turtle: String,
    reptil: String,
    pez: String,
    indt: String,
    txn_expl: String,
    investigador_zoo: String,
    cabeza_nofig: String,
    sau_nofig: String,
    feli_nofig: String,
    bat_nofig: String,
    erguida_nofig: String,
    prim_nofig: String,
    cabfigint: String,
    cabhoc: String,
    garra: String,
    otfigind: String,
    forma_funcion: String,
    marcas_uso: String,
    desc_marcas_uso: String,
    tipo_ceramico_grupo: String,
    ceramico_refz: String,
    periodo_ceramica: String,
    fase_ceramica: String,
    temporalidad_ceramica: String,
    procedencia_ceramica: String,
    estado_conservacion: String,
    potencial: String,
    potencial_exp: String,
    largo: String,
    ancho: String,
    alto: String,
    peso: String,
    nombre_invest: String,
    fecha_analisis: String,
    fotos_num: String

});

module.exports = mongoose.model('Ceramic', CeramicSchema);
// Ceramics guarda documentos con esta estructura en la coleccion

