'use strict'

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var ContextoSchema = Schema({
    
 
    date: { type: Date, default: Date.now },
    image: String,
    title: String,
    content: String,
    id_cont: String,
    proyecto: String,
    year_inv: Number,
    investigador: String,
    sector: String,
    ubicacion: String,
    operacion: Date,
    suboperacion: String,
    desc_operacion: String,
    contexto: String,
    diagnostico_contexto: String,
    tipo_contexto: String,
    otro_contexto: String,
    num_cem: String,
    num_basa: String,
    num_plaza: String,
    num_estruc: String,
    ind_conex: String,
    foto: String,
    num_foto: String,
    calidad_foto: String,
    estado_foto: String,
    planimetria: String,
    num_lamina: String,
    calidad_plano: String,
    estado_plano: String,
    coordenadas: String,
    crtm: String,
    profundidad: String,
    profundidad_datum: String,
    ubicacion_datum: String,
    existe_antro: String,
    estado_antro: String,
    tipo_enterramiento: String,
    forma_enterramiento: String,
    condicion: String,
    sexo:String,
    edad:Number,
    patologias:String,
    evidencia: String,
    fecha_existe: String,
    tecnica: String,
    material_fechado: String,
    asociacion_indv: String,
    asociacion_art: String,
    num_lab: String,
    fecha_conv: String,
    fecha_calb: String,
    valoracion_fecha: String,
    explique_fecha: String,
    otras_muestras: String,
    estado_muestras: String,
    cera_existe: String,
    cera_cant: String,
    id_artef_cera: String,
    litica_existe: String,
    litica_cant: String,
    id_litica: String,
    metal_existe: String,
    metal_cantidad: String,
    metal_id: String,
    madera_existe: String,
    madera_cantidad: String,
    madera_id: String,
    fauna_existe: String,
    fauna_cantidad: String,
    fauna_id: String,
    otros_existe: String,
    otros_cantidad: String,
    otros_id: String,
    verifica_si: String,
    inves_verifica: String,
    fecha_verifica: Date,
    resultados_verifica: String,
    revisor_documental: String,
    fecha_revision: Date    

});

module.exports = mongoose.model('Contexto', ContextoSchema);
// Ceramics guarda documentos con esta estructura en la coleccion

