'use strict'

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var MetalicoSchema = Schema({
    
    date: { type: Date, default: Date.now },
    // image: String,
    title: String,
    content: String,
    cod_mon: String,
    num_artefacto: Number,
    num_caja: Number,
    proyecto: String,
    investigador: String,
    pro_year: Number,
    etiqueta: String,
    fecha_exc: Date,
    id_contexto: String,
    contexto: String,
    ubicacion: String,
    foto: String,
    num_foto: String,
    calidad_foto: String,
    estado_foto: String,
    plano: String,
    num_lamina: String,
    calidad_lamina: String,
    estado_Lamina: String,
    diagnostico_contexto: String,
    fechamiento: String,
    tipo_pieza: String,
    desc_narrativa: String,
    materia_prima: String,
    lineas: String,
    greca: String,
    elemento_secuencia: String,
    otro_nofig: String,
    cab_zoo: String,
    suario_zoo: String,
    felino_zoo: String,
    batracio_zoo: String,
    ave_zoo: String,
    primate_zoo: String,
    murcielago_zoo: String,
    mamifero_zoo: String,
    turtle_zoo: String,
    reptil_zoo: String,
    pez_zoo: String,
    armadillo_zoo: String,
    insecto_zoo: String,
    ciervo_zoo: String,
    canino_zoo: String,
    ind_zoo: String,
    tax_zoo: String,
    inv_zoo: String,
    cab_antro: String,
    cab_tocantro: String,
    masc_antro: String,
    atuendo_antro: String,
    cara_antro: String,
    sedente_antro: String,
    erguida_antro: String,
    supino_antro: String,
    escena_antro: String,
    genero_antro: String,
    anomalia_antro: String,
    cab_ind: String,
    cara_ind: String,
    otro_ind: String,
    uso_funcion: String,
    datos_funcionalidad: String,
    datos_func_exp: String,
    referencias_funcional: String,
    periodo_funcional:  String,
    fase_funcional: String,
    temporalidad_funcional: String,
    procedencia_funcional: String,
    estado_conservacion: String,
    potencial: String,
    potencial_exp: String,
    largo: String,
    ancho: String,
    alto: String,
    peso: String,
    nombre_invest: String,
    fecha_analisis: String,
    fotos_num: String 

});

module.exports = mongoose.model('Metalico', MetalicoSchema);
// Litico guarda documentos con esta estructura en la coleccion

