import { Component, OnInit } from '@angular/core';
import Swal from 'sweetalert2';
import { SitioService } from 'src/app/services/sitio.service';
import { Router, ActivatedRoute, Params} from '@angular/router';
import { Sitio } from 'src/app/models/sitio';
import { Globals } from 'src/app/services/globals';

@Component({
  selector: 'app-ficha-origenes',
  templateUrl: './ficha-origenes.component.html',
  styleUrls: ['./ficha-origenes.component.css'],
  providers: [SitioService]
})
export class FichaOrigenesComponent implements OnInit {
   user:any;
   sitio!: Sitio;
   status!: string;
   url: string;
   is_edit: boolean;

  afuConfig = {
    maxSize: 2,
    uploadAPI: {
      url:Globals.url+'upload-image'
    },
    replaceTexts: {
      selectFileBtn: 'Seleccione Archivo',
      resetBtn: 'Resetear',
      uploadBtn: 'Subir',
      dragNDropBox: 'Arrastre y soltar',
      attachPinBtn: 'Subiendo Archivo...',
      afterUploadMsg_success: 'Archivo Subido !',
      afterUploadMsg_error: 'Fallo en el proceso !',
      sizeLimit: 'Tamaño Máximo'
    }
  };
  constructor(
    private _route: ActivatedRoute,
    private _router: Router,
    private _sitioService: SitioService
  ) {
    this.url = Globals.url;
    this.is_edit = true;

    this.sitio={
       _id:'',
         date:'',
         image:'',
         numero_caso:'',
         nombre_sitio: '',
         clave_sitio: '',
         hallazgo: '',
         fecha_registro:'',
         registrador: '',
         regional: false,
         subregional:false,
         inspeccion: false,
         evaluacion: false,
         rescate: false,
         mncr: false,
         ucr: false,
         consultoria: false,
         literatura: false,
         provincia: '',
         canton: '',
         distrito:'',
         region: '',
         altitud:'',
         arquitectonico: false,
         basurero: false,
         conchero: false,
         funerario: false,
         habitacion: false,
         petroglifo: false,
         salina: false,
         taller: false,
         camino: false,
         excavacion: false,
         arbitratia: false,
         probabilistico: false,
         horizontal: false,
         sondeo: false,
         trinchera: false,
         ceramica: false,
         litica: false,
         tierra: false,
         carbon: false,
         fauna: false,
         flora: false,
         oro: false,
         jade: false,
         cobre: false,
         vidrio: false,
         porcelana: false,
         hierro: false,
         lapidaria: false,
         esferas: false,
         pisos: false,
         tesis: false,
         monografia: false,
         publicacion: false,
         titulo: '',
         artefactos: false,
         croquis: false,
         planos: false,
         dibujos: false,
         video: false,
         latitude:0,
         Logitude: 0,
         coordenadas: '',
         google: '',
         id_google: '',
         coordenadas_google: '',
         num_consecutivo: '',
         reportes: '',
         direccion: '',
         huaqueado: false,
         sembrado: false,
         excavacion_aislada: false,
         parques_nacionales: false,
         hoja_cartografica: '',
         lambert_oe: '',
         lambert_ns:'',
         grad_lat: '',
         min_lat: '',
         seg_lat: '',
         grad_long: '',
         min_long: '',
         seg_log: '',
         localizacion_gps: false,
         area_estimada: '',
         zona_vida: '',
         abrigo_cueva_caverna: false,
         mil_dos_ocho_mi_ac: false,
         coordenada_convert: '',
         ocho_mil_cuatro_mil_ac: false,
         cuatro_mil_mil_quinientos_ac: false,
         mil_quinientos_quinientos_ac: false,
         crtm05_e: '',
         quinientos_trecientos_dc: false,
         trecientos_ochocientos_dc: false,
         ochocientos_mil_tres_cincuenta_dc: false,
         mil_tres_cincuenta_mil_quinientos_dc: false,
         mil_quinientos_mil_ochocientos_dc: false,
         mil_ochocientos_mil_novecientos_sc: false,
         lev_cartografico: false,
         rec_superficie: false,
         cala_estratatigrafica: false,
         limpieza_perfiles: false,
         limpieza_razgos: false,
         huesos_humanos: false,
         madera_fibra: false,
         arcilla_cocida: false,
         litica_dat: false,
         ceramica_dat: false,
         radiocarbono_dat: false,
         hoja_registro: false,
         material_fotografico: false,
         id_google_comillas: '',
         diarios_campo: false,
         documento_kml: '',
         nombre_sitio_google: '',
         crtm05_n: '',
         rio_cercano: '',
         levantamiento_cartografico: '',
         fase_9: '',
         arado: false,
         bibliografia: '',
         biodeterioro: false,
         catalogo_sitios_ucr: false,
         causa_penal: '',
         clave_antigua: '',
         composicion_cronologica: false,
         concha: false,
         construccion: false,
         erosion: false,
         estado_conservacion: '',
         estatuaria: false,
         estudio_impacto_ambiental: false,
         expediente_setena: '',
         fase_1: '',
         fase_2: '',
         fase_3: '',
         fase_4: '',
         fase_5: '',
         fase_6: '',
         fase_7: '',
         fase_8: '',
         fase_10: '',
         fecha_digitacion: '',
         fundacion: false,
         ice: false,
         investigador: '',
         loza: false,
         materiales_dispersos: false,
         mecanizado: false,
         meteorizacion: false,
         monitoreo_mov_tierras: false,
         no_perturbado: false,
         otra: '',
         otro: '',
         otro_m: '',
         otro_r: '',
         otro_rec_superficie: '',
         otr_tc: '',
         otro_tipo_proyecto: '',
         otro_ts: '',
         otros: '',
         otros_da: '',
         paisajes_culturales_sumergidos: false,
         pastoreo: false,
         peritaje: false,
         registro_numero: '',
         plano_catrasto: '',
         profundidad_depositos: '',
         recorrido_propiedad: false,
         registro_fotografico: false,
         reserva_arqueologica: false,
         resina: false,
         restos_barcos: false,
         ruinas_asentamientos: false,
         territorio_indigena: false,
         trabajo_graduacion: false,
         vestigios_cavernas: false,
         fechamiento_adiometrico: '',
         sitios_marina: false,
         informe: false
    }
   }

  ngOnInit(): void {
  }

}

  